#!/usr/bin/env python

from collections import defaultdict
import sys
import re
from pathlib import Path


PATTERN: re.Pattern[str] = re.compile(
    r'^\s*#define\s+'
    r'(?:[a-zA-Z_][0-9a-zA-Z_]*)\s+'
    r'(?P<module_name>[a-zA-Z_][0-9a-zA-Z_]*)_LTX_(?P<method_name>[a-zA-Z_][0-9a-zA-Z_]*)\s*$'
)


def main() -> None:
    it = iter(sys.argv)
    _ = next(it)

    output = Path(next(it))
    inputs_i = (Path(n) for n in it)

    modules: defaultdict[str, list[str]] = defaultdict(list)

    for in_path in inputs_i:
        with in_path.open('r', encoding='utf-8', errors='replace') as f:
            for line in f:
                m = PATTERN.match(line)
                if not m:
                    continue
                mm = m.groupdict()
                modules[mm['module_name']].append(mm['method_name'])

    with output.open('w') as f:
        f.write('/* Generated by gen_symb_table.py. Do not edit. */\n\n')

        f.write('#include <mcrypt_internal.h>\n\n')

        f.write('/* Method stubs (generic signatures used to satisfy linker) */\n')
        for module, methods in modules.items():
            for method in methods:
                f.write(f'extern void {module}_LTX_{method}(void);\n')

        f.write('\n/* Method table */\n')
        f.write('const mcrypt_preloaded mps[] = {\n')
        for module, methods in modules.items():
            f.write(f'    {{"{module}", NULL}},\n')
            for method in methods:
                f.write(f'    {{"{module}_LTX_{method}", {module}_LTX_{method}}},\n')
        f.write('    {NULL, NULL},\n};\n')


if __name__ == '__main__':
    main()
