#!/usr/bin/env python

from argparse import ArgumentParser, Namespace
from collections import defaultdict
from pathlib import Path
from re import Pattern, compile as re_compile


# Matches any line that looks like `#define something blah_LTX_blahblah`
# optionally with arbitrary amount of paddings.
METHOD_ENTRY_PATTERN: Pattern[str] = re_compile(
    r'^\s*#define\s+'
    r'(?:[a-zA-Z_][0-9a-zA-Z_]*)\s+'
    r'(?P<method_name>(?:[a-zA-Z_][0-9a-zA-Z_]*)_LTX_(?:[a-zA-Z_][0-9a-zA-Z_]*))\s*$'
)


def parse_args() -> tuple[ArgumentParser, Namespace]:
    p = ArgumentParser()
    p.add_argument('modules', nargs='+', type=Path, help='module files')
    p.add_argument('-o', '--output', required=True, help='output file')

    return p, p.parse_args()


def main() -> None:
    _, args = parse_args()

    output = Path(args.output)
    inputs_i = (Path(n) for n in args.modules)

    modules: defaultdict[str, list[str]] = defaultdict(list)

    for in_path in inputs_i:
        with in_path.open('r', encoding='utf-8', errors='replace') as f:
            module_name = in_path.stem
            for line in f:
                m = METHOD_ENTRY_PATTERN.match(line)
                if not m:
                    continue
                mm = m.groupdict()
                modules[module_name].append(mm['method_name'])

    with output.open('w') as f:
        f.write('/* Generated by gen_symb_table.py. Do not edit. */\n\n')

        f.write('#include <mcrypt_internal.h>\n\n')

        f.write('/* Method stubs (generic signatures used to satisfy linker) */\n')
        for module, methods in modules.items():
            for method in methods:
                f.write(f'extern void {method}(void);\n')

        f.write('\n/* Method table */\n')
        f.write('const mcrypt_preloaded mps[] = {\n')
        for module, methods in modules.items():
            f.write(f'    {{"{module}", NULL}},\n')
            for method in methods:
                f.write(f'    {{"{method}", {method}}},\n')
        f.write('    {NULL, NULL},\n};\n')


if __name__ == '__main__':
    main()
